name: Snyk Security Scan

on:
  push:
    branches:
      - main  # Runs this workflow when you push to the main branch

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use the correct Node.js version for your project

      - name: Install dependencies
        run: npm install  # This requires package.json in your repo

      - name: Run Snyk scan
        uses: snyk/actions/node@master
        with:
          args: test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
